number: 123

issuedAt: 2023-10-01T12:00:00Z

currency: "USD"

organization:
  name: "My Organization"
  address: "123 Main St, City, Country"
  taxId: "123456789"
  description: "A brief description of the organization."

counterparty:
  name: "Client Name"
  address: "456 Client St, City, Country"
  taxId: "987654321"
  description: |
    Sample Client Company
    789 Client Ave, City, Country

description: |
  Frontend software development services according to _INDEPENDENT CONTRACTOR AGREEMENT
  dated XXth day of Month, 2023_

  #### Bank details for USD transfer
  **Beneficiary’s Bank:** Bank name, City, Country
  **Beneficiary SWIFT:** BANKSWIFT
  **Ben’s IBAN:** US12BANK12345678901234
  **Name of Beneficiary:** P/E Name Surname

  ##### Intermediary Bank
  Sample Bank
  Somewhere, Country
  SWIFT

  ##### Intermediary Bank
  Sample Bank
  Somewhere, Country
  SWIFT

services:
  - name: "Service 1"
    amount: 123.45
  - name: "Service 2"
    amount: 67.89
