issuedAt: 2023-10-01T12:00:00Z

currency: "USD"

organization:
  name: "My Organization"
  address: "123 Main St, City, Country"
  taxId: "123456789"
  description: "A brief description of the organization."

counterparty:
  name: "Client Name"
  address: "456 Client St, City, Country"
  taxId: "987654321"

services:
  - name: "Service 1"
    amount: 123.45
  - name: "Service 2"
    amount: 67.89
